### ISSUE TITLE
Change existing cursor to a new one

### ISSUE THREAD

**Issue by BerendPronk** [rijkvanzanten/luaus#26]
https://previews.123rf.com/images/marigranula/marigranula1203/marigranula120300280/12657766-hand-pointing-up-Stock-Photo-finger.jpg

**Comment by BerendPronk** [comment]
Still needed? I kinda like the current one. Though it probably isn't free for us to use.

**Comment by rijkvanzanten** [comment]
We'll keep it as is for now.
