### ISSUE TITLE
It's not clear what this project will do when it's finished

### ISSUE THREAD

**Issue by Razpudding** [rijkvanzanten/luaus#37]
You claim it will keep track of your game scores; but how? You haven't explained how this will be done with a physical button at all 😛 

I can't make out from the description or the whishlist what this thing will do. What lobby? What box? 😕 

I want to give you guys feedback but I can't really at this point. Which you probably already know. Might be a good idea to explain your app on monday and get some feedback on it then.

**Comment by BerendPronk** [comment]
Our final README.md will be self-explanatory. Apologies for the inconvenience!
