### ISSUE TITLE
Help me grade this :shit:

### ISSUE THREAD

**Issue by Razpudding** [rijkvanzanten/luaus#39]
It looks like it's going to be something pretty cool, but how the hell am I supposed to understand it, let alone grade it?

Here's how I think you can help me out:

- Draw up a diagram showing the different components of your setup (both the physical an digital, so include the nodeMCU, look at the Lightboard diagram from the slides in week 1 for a reference)
- Explain what one roundtrip looks like within this setup (possibly using a flow diagram)
- List other possible use cases
- Document who did what (if possible)

**Comment by Razpudding** [comment]
And add some code comments for crying out loud!

**Comment by rijkvanzanten** [comment]
💩

**Comment by BerendPronk** [comment]
Will do!
