### ISSUE TITLE
Fix mobile flow (from overview to controller)

### ISSUE THREAD

**Issue by BerendPronk** [rijkvanzanten/luaus#49]
Styling seems to be off a bit on iPhone 5 devices, and the form can't receive any input

**Comment by BerendPronk** [comment]
Styling needs to be reverted first, in order for us to check on this issue

**Comment by BerendPronk** [comment]
With the implementation of vDom, the mobile flow is still broken, unfortunately.

**Comment by rijkvanzanten** [comment]
This is definitely a styling problem, not a vDom specific issue. vDom just creates the HTML output and has nothing to do with the styling

**Comment by BerendPronk** [comment]
Yes, I reduced it to that already by mentioning that it is still broken after that update. The only troubling thing is that the user is unable to enter a name on mobile devices. Maybe the background animation is too heavy?

**Comment by rijkvanzanten** [comment]
Hmm. I'll look into the input. I'm moving that to a separate issue. #81
